const livros = [
  {
    id: 1,
    nome: 'Digital minimalism',
    autor: 'Cal Newport',
    categoria: 'Produtividade',
    paginas: 254,
    recomenda: false,
    leu: false,
  },
  {
    id: 2,
    nome: 'Sistemas Digitais',
    autor: 'Ronal J Tocci, NealS. Winder',
    categoria: 'Tecnologia',
    paginas: 819,
    recomenda: true,
    leu: true,
  },
  {
    id: 3,
    nome: 'Engenheiria de Software',
    autor: 'Sommerville',
    categoria: 'Tecnologia',
    paginas: 529,
    recomenda: true,
    leu: true,
  },
  {
    id: 4,
    nome: 'Reiki',
    autor: "'Johnny de'Carli",
    categoria: 'Energias',
    paginas: 528,
    recomenda: true,
    leu: true,
  },
  {
    id: 5,
    nome: 'Abra seus Olhos',
    autor: 'Tatiana Gebrael',
    categoria: 'Desenvolvimento',
    paginas: 237,
    recomenda: true,
    leu: true,
  },
  {
    id: 6,
    nome: 'O Evangelho Segundo o Espiritismo',
    autor: 'Allan Kardec',
    categoria: 'Espiritismo',
    paginas: 317,
    recomenda: true,
    leu: false,
  },
  {
    id: 7,
    nome: 'Scrum',
    autor: 'Cesar Brod',
    categoria: 'Metodologias Ageis',
    paginas: 197,
    recomenda: false,
    leu: true,
  },
];

module.exports = livros;
